# Analysis and interpretation of your results {#sec-analysing}

+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+
| # Open Research practice                                                                                                                                                 | # Links to resources                                                                                                                                                       | # Alignment with FAIR |
|                                                                                                                                                                          |                                                                                                                                                                            |                       |
| Use open source statistical software                                                                                                                                     | List of [open-source statistical software](https://en.wikipedia.org/wiki/List_of_statistical_software#Open-source)                                                         | Reusable              |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+
| Make all code and scripts used in the analysis of results available, including statistical analysis, data transformation, visualisation, and any automation of processes | [NCRM To share or not to share: code sharing in social science](https://www.ncrm.ac.uk/news/show.php?article=5705)                                                         | Reusable              |
|                                                                                                                                                                          |                                                                                                                                                                            |                       |
|                                                                                                                                                                          | [The Turing Way: A handbook for reproducible, ethical and collaborative research: reproducible code](https://book.the-turing-way.org/reproducible-research/code-reuse)     |                       |
|                                                                                                                                                                          |                                                                                                                                                                            |                       |
|                                                                                                                                                                          | [A Practical Iterative Framework for Qualitative Data Analysis](https://doi.org/10.1177/160940690900800107)                                                                |                       |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+
| If you pre-registered your study, revisit the planned analysis methods and document any deviations during the analysis stage                                             | UKRN Primer: [Pre-registration and Registered Reports](https://osf.io/8v2n7)                                                                                               | Findable & Reusable   |
|                                                                                                                                                                          |                                                                                                                                                                            |                       |
|                                                                                                                                                                          | National Cyber Security guidance: [Produce clean & maintainable code](https://www.ncsc.gov.uk/collection/developers-collection/principles/produce-clean-maintainable-code) |                       |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+

Next section: [Sharing your results](Sharing.qmd#sec-sharing)
