# **Conducting your research project** {#sec-conducting}

+------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------+
| Open Research practice                                                                         | Links to resources                                                                                                                                                                                                               | Alignment with FAIR      |
+================================================================================================+==================================================================================================================================================================================================================================+==========================+
| Develop a pre-registration document                                                            | UKRN Primer: [Pre-registration and Registered Reports](https://osf.io/8v2n7)                                                                                                                                                     | Findable & Accessible    |
+------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------+
| Use open source software and tools                                                             | UKRN open software and code [open software & code animation](https://www.youtube.com/watch?v=o_9ctpM61sM&feature=youtu.be) (3 minutes) and [open software & code video](https://www.youtube.com/watch?v=cD1hSbHpdKE) (8 minutes) | Interoperable & Reusable |
|                                                                                                |                                                                                                                                                                                                                                  |                          |
|                                                                                                | UKRN Primer: [Open Code and Software](https://osf.io/qw9ck)                                                                                                                                                                      |                          |
+------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------+
| Document your data collection process                                                          | FOSTER course: [Managing & Sharing Research Data](https://openplato.eu/mod/scorm/view.php?id=1278) (click to 'Access as a guest')                                                                                                | Findable & Reusable      |
|                                                                                                |                                                                                                                                                                                                                                  |                          |
|                                                                                                | [The Turing Way: A handbook for reproducible, ethical and collaborative research: open notebooks](https://book.the-turing-way.org/reproducible-research/open/open-notebooks)                                                     |                          |
+------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------+
| Upload your (anonymised if appropriate) research data to a trusted open access data repository | FOSTER course: [assessing the FAIR-ness of data](https://openplato.eu/mod/scorm/view.php?id=1401) (click to 'Access as a guest')                                                                                                 | Accessible & Reusable    |
+------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------+
| Share preliminary findings via preprints and conference presentations                          | UKRN [preprints animation](https://www.youtube.com/watch?v=syef3PPltG0) (3 minutes) and [preprints video](https://www.youtube.com/watch?v=MqX_i5SFkC0) (6 minutes)                                                               | Findable & Accessible    |
|                                                                                                |                                                                                                                                                                                                                                  |                          |
|                                                                                                | UKRN Primer: [Preprints](https://osf.io/m4zyh)                                                                                                                                                                                   |                          |
+------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------+

Next section: [Analysis and interpretation of your results](Analysing.qmd#sec-analysing)
