# Evaluation and impact {#sec-evaluating}

+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------+---------------------+
| Open Research practice                                                                                                                                                                                                                                               | Links to resources                                                                                          | Alignment with FAIR |
+======================================================================================================================================================================================================================================================================+=============================================================================================================+=====================+
| Track the number of times your research data has been downloaded from open repositories                                                                                                                                                                              | Check your dataset record in each repository for the number of downloads                                    | Findable            |
|                                                                                                                                                                                                                                                                      |                                                                                                             |                     |
| As with all metrics, numbers only tell part of the story and should be used to support expert judgement; the number of downloads will be affected by discipline and year of publication                                                                              |                                                                                                             |                     |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------+---------------------+
| Document and share examples of your research impacting policy                                                                                                                                                                                                        | [Fast Track Impact](https://www.fasttrackimpact.com/)                                                       | Accessible          |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------+---------------------+
| Studies by other researchers building on your work, enabled by open data and sharing your code                                                                                                                                                                       | The Turing Way: A handbook for reproducible, ethical and collaborative research                             | Accessible          |
|                                                                                                                                                                                                                                                                      |                                                                                                             |                     |
|                                                                                                                                                                                                                                                                      | [Data](https://the-turing-way.netlify.app/reproducible-research/rdm/rdm-sharing)                            |                     |
|                                                                                                                                                                                                                                                                      |                                                                                                             |                     |
|                                                                                                                                                                                                                                                                      | [Code](https://the-turing-way.netlify.app/reproducible-research/code-reuse)                                 |                     |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------+---------------------+
| Altmetrics track mentions of your research on social media, news outlets and policy documents. This provides a broader picture of the reach and influence of your research beyond traditional academic citations                                                     | University of Southampton Library: [altmetrics](https://library.soton.ac.uk/bibliometrics/altmetrics/guide) | Findable            |
|                                                                                                                                                                                                                                                                      |                                                                                                             |                     |
| Altmetrics should only be used as a guide for how much attention a research output is receiving relative to similarly aged outputs; high scores are indicative of high engagement, but altmetrics cannot tell the difference between negative and positive attention |                                                                                                             |                     |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------+---------------------+

Next section: [Further resources](Resources.qmd#sec-resources)
