# Securing funding and building your research team {#sec-funding}

### A note about research data

Your research data is the information you collect, observe or generate to support and validate your findings.

-   **Evidence-based**: Research data serves as the foundation for research. It's what allows researchers to build a case for their findings and conclusions. 
-   **Varied formats**: Data can come in many forms and can be digital and non-digital. For example, research may involve experimental data, surveys or field studies, observational data, reusing existing datasets, textual analysis, archival research, qualitatative data or artworks.

+--------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Open Research practice                                                                                                               | Links to resources                                                                                                                                          | Alignment with FAIR                                                                                                                                                           |
+======================================================================================================================================+=============================================================================================================================================================+===============================================================================================================================================================================+
| State your intention to **share data openly**, outlining specific **data types** and **access conditions**                           | UKRN Primer [Data sharing](https://osf.io/wp4zu)                                                                                                            | Accessible & Interoperable                                                                                                                                                    |
+--------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Name your chosen **data repository** and outline your **data management plans** for during and after the project including file type | Digital Curation Centre: [Data Management Plans](https://www.dcc.ac.uk/guidance/how-guides/develop-data-plan)                                               | Findable & Interoperable                                                                                                                                                      |
+--------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Commit to making your research findings **open access** (via publisher or repository routes)                                         | UKRN Open Access [animation](https://www.youtube.com/watch?v=RncrQXbnL3c) (3 minutes) and [video](https://www.youtube.com/watch?v=YX-7kseGimY) (10 minutes) | Accessible                                                                                                                                                                    |
|                                                                                                                                      |                                                                                                                                                             |                                                                                                                                                                               |
|                                                                                                                                      | UKRN Primer: [Open Access](https://osf.io/94rsp)                                                                                                            |                                                                                                                                                                               |
+--------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Explain your commitment to **transparent and replicable research methods**                                                           | [Sharing the Recipe: Reproducibility and Replicability in Research Across Disciplines](https://doi.org/10.3897/rio.8.e89980)                                | While not directly addressing with FAIR principles, this promotes transparency (by referencing open methodology resources) and reproducibility (by pre-registering the study) |
+--------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

Next section: [Conducting your research](Conducting.qmd#sec-conducting)
