# **Planning your research project** {#sec-planning}

In the planning phase you will identify and develop your research questions, and may conduct related tasks including literature reviews, formulating research hypotheses or considering design methodologies.

+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------+
| **Open Research practice**                                                                                                                                                                                                                                    | **Links to resources**                                                                                                                                         | **Alignment with FAIR** |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------+
| Engaging with **pre-registered studies and protocols** allows early insight into research plans and methodology, reducing duplication of efforts and eliminating [HARKing](https://en.wikipedia.org/wiki/HARKing) (Hypothesizing After the Results are Known) | UKRI Preregistration [animation](https://www.youtube.com/watch?v=h0Pin-OUlS4) (3 minutes) and [video](https://www.youtube.com/watch?v=q4yf7Pt4q5c) (9 minutes) | Findable & Accessible   |
|                                                                                                                                                                                                                                                               |                                                                                                                                                                |                         |
|                                                                                                                                                                                                                                                               | Open Science Framework: [Preregistration](https://help.osf.io/article/145-preregistration)                                                                     |                         |
|                                                                                                                                                                                                                                                               |                                                                                                                                                                |                         |
|                                                                                                                                                                                                                                                               | UKRN Primer: [Pre-registration and Registered Reports](https://osf.io/8v2n7)                                                                                   |                         |
|                                                                                                                                                                                                                                                               |                                                                                                                                                                |                         |
|                                                                                                                                                                                                                                                               | [PROSPERO](https://www.crd.york.ac.uk/PROSPERO/) (systematic review protocols)                                                                                 |                         |
|                                                                                                                                                                                                                                                               |                                                                                                                                                                |                         |
|                                                                                                                                                                                                                                                               | [Study Preregistration: a How-To Guide](https://doi.org/10.31234/osf.io/6g5zv) written for students                                                            |                         |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------+
| Using existing **open datasets** can inspire new research questions and applications. Examining data trends and patterns can guide the development of focused research plans and hypotheses                                                                   | UK Data Service: [new to using data](https://ukdataservice.ac.uk/learning-hub/new-to-using-data/)                                                              | Accessible & Reusable   |
|                                                                                                                                                                                                                                                               |                                                                                                                                                                |                         |
|                                                                                                                                                                                                                                                               | UKRN Data sharing [video](https://www.youtube.com/watch?v=-s47Wb4WvDA) (20 minutes)                                                                            |                         |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------+
| Open peer review practices can encourage early feedback on research proposals, potentially improving the quality and focus of the planned project. It creates trust in the review process, and gives credit to reviewers                                      | FOSTER course: [Open Peer Review](https://openplato.eu/mod/scorm/view.php?id=12) (click to 'Access as a guest')                                                | Findable                |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------+

Next section: [Securing funding and building your research team](Funding.qmd#sec-funding)
